name: Notify Discord on PR Commit

on:
  pull_request:
    types: [synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR commit info to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"content\": \"🔄 PR에 새 커밋이 올라왔습니다!\nPR 제목: ${{ github.event.pull_request.title }}\n작성자: ${{ github.actor }}\n커밋 수: ${{ github.event.pull_request.commits }}\n링크: ${{ github.event.pull_request.html_url }}\"
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
