name: Notify Discord on PR Review

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR review info to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"content\": \"📝 PR 리뷰가 제출되었습니다!\nPR 제목: ${{ github.event.pull_request.title }}\n작성자: ${{ github.actor }}\n리뷰 상태: ${{ github.event.review.state }}\n링크: ${{ github.event.pull_request.html_url }}\" 
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
